version: '3.9'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "20447:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_app
    restart: always
    volumes:
      - .:/code
    ports:
      - "10620:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=5432
    depends_on:
      - db
    command: >
       sh -c "echo 'Waiting for PostgreSQL...' &&
         while ! nc -z db 5432; do sleep 1; done &&
         echo 'PostgreSQL is up!' &&
         python manage.py migrate &&
         gunicorn project.wsgi:application --bind 0.0.0.0:8000"

volumes:
  postgres_data:
