# Generated by Django 5.1 on 2024-12-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("product_code", models.CharField(max_length=100, unique=True)),
                ("product_name", models.CharField(max_length=255)),
                ("price", models.PositiveIntegerField()),
                ("stock", models.PositiveIntegerField()),
            ],
        ),
    ]
