# Generated by Django 5.1 on 2024-12-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopsales", "0002_alter_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
