# Generated by Django 5.1 on 2024-12-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopsales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
